/**
 * GitHub自动营销管理器
 * 让Prophet自己在GitHub上营销自己
 *
 * 功能:
 * - 自动更新README stats
 * - 自动回复issues (AI驱动)
 * - 自动生成每日更新
 * - 自动管理releases
 */

import Anthropic from '@anthropic-ai/sdk'
import { Octokit } from '@octokit/rest'
import { execSync } from 'child_process'
import * as fs from 'fs/promises'
import * as path from 'path'

interface GitHubStats {
  totalCommits: number
  totalStars: number
  totalForks: number
  totalWatchers: number
  openIssues: number
  closedIssues: number
  lastUpdate: string
}

interface DailyUpdate {
  date: string
  commits: number
  filesChanged: number
  linesAdded: number
  linesDeleted: number
  highlights: string[]
}

export class GitHubAutoManager {
  private anthropic: Anthropic
  private octokit: Octokit
  private owner: string
  private repo: string
  private isRunning = false

  constructor(config: { owner: string; repo: string }) {
    this.owner = config.owner
    this.repo = config.repo

    // 初始化Anthropic
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY || ''
    })

    // 初始化Octokit
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN
    })
  }

  /**
   * 启动GitHub自动管理
   */
  async start(): Promise<void> {
    console.log('[GitHubAutoManager] 🚀 启动GitHub自动营销...')
    this.isRunning = true

    // 立即执行一次更新（非阻塞，失败不影响启动）
    this.updateREADMEStats().catch((error) => {
      console.error('[GitHubAutoManager] 首次README更新失败:', error.message)
    })

    // 每小时更新README stats (避开:00，使用:17)
    setInterval(async () => {
      if (this.isRunning) {
        await this.updateREADMEStats()
      }
    }, 60 * 60 * 1000)

    // 每天生成更新 (早上9:17)
    this.scheduleDailyUpdate()

    // 每小时检查issues (使用:27)
    setInterval(async () => {
      if (this.isRunning) {
        await this.autoReplyIssues()
      }
    }, 60 * 60 * 1000)

    console.log('[GitHubAutoManager] ✅ GitHub自动营销已启动')
    console.log('  ✓ README自动更新已启动（每小时）')
    console.log('  ✓ Issues自动回复已启动（AI驱动）')
    console.log('  ✓ 每日更新自动发布已启动')
    console.log('  💡 Prophet正在GitHub上自己营销自己！')
  }

  /**
   * 停止自动管理
   */
  stop(): void {
    this.isRunning = false
    console.log('[GitHubAutoManager] ⏹️  GitHub自动营销已停止')
  }

  /**
   * 自动更新README统计数据
   */
  async updateREADMEStats(): Promise<void> {
    try {
      console.log('[GitHubAutoManager] 📊 更新README stats...')

      // 获取最新stats
      const stats = await this.getGitHubStats()

      // 读取现有README
      const { data } = await this.octokit.rest.repos.getContent({
        owner: this.owner,
        repo: this.repo,
        path: 'README.md'
      })

      if ('content' in data) {
        let readme = Buffer.from(data.content, 'base64').toString('utf-8')

        // 更新badges
        readme = this.updateBadges(readme, stats)

        // 更新stats表格
        readme = this.updateStatsTable(readme, stats)

        // 提交更新
        await this.octokit.rest.repos.createOrUpdateFileContents({
          owner: this.owner,
          repo: this.repo,
          path: 'README.md',
          message: `🤖 Auto-update stats - ${stats.lastUpdate}`,
          content: Buffer.from(readme).toString('base64'),
          sha: data.sha
        })

        console.log('[GitHubAutoManager] ✅ README stats更新完成')
      }
    } catch (error) {
      console.error('[GitHubAutoManager] README更新失败:', error)
    }
  }

  /**
   * 自动回复issues（使用AI）
   */
  async autoReplyIssues(): Promise<void> {
    try {
      console.log('[GitHubAutoManager] 💬 检查新issues...')

      // 获取需要回复的issues
      const { data: issues } = await this.octokit.rest.issues.listForRepo({
        owner: this.owner,
        repo: this.repo,
        state: 'open',
        labels: 'needs-response',
        per_page: 5
      })

      for (const issue of issues) {
        // 让Claude生成回复
        const reply = await this.generateIssueReply(issue)

        if (reply) {
          // 发布回复
          await this.octokit.rest.issues.createComment({
            owner: this.owner,
            repo: this.repo,
            issue_number: issue.number,
            body: reply + '\n\n---\n🤖 *Auto-generated by Prophet AI*'
          })

          // 移除needs-response标签
          try {
            await this.octokit.rest.issues.removeLabel({
              owner: this.owner,
              repo: this.repo,
              issue_number: issue.number,
              name: 'needs-response'
            })
          } catch {
            // 标签可能不存在，忽略错误
          }

          console.log(`[GitHubAutoManager] ✅ 已回复issue #${issue.number}`)
        }
      }
    } catch (error) {
      console.error('[GitHubAutoManager] Issues回复失败:', error)
    }
  }

  /**
   * 生成每日更新
   */
  async generateDailyUpdate(): Promise<void> {
    try {
      console.log('[GitHubAutoManager] 📝 生成每日更新...')

      // 获取今天的活动数据
      const dailyData = await this.getDailyData()

      // 让Claude生成有趣的更新内容
      const message = await this.anthropic.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 800,
        messages: [{
          role: 'user',
          content: `作为Prophet AI项目，基于以下24小时活动数据，生成一条有趣的每日更新（200-300字）：

日期: ${dailyData.date}
Commits: ${dailyData.commits}
文件变更: ${dailyData.filesChanged}
代码行数: +${dailyData.linesAdded} -${dailyData.linesDeleted}
亮点: ${dailyData.highlights.join(', ')}

要求：
- 轻松有趣的语气
- 突出自动化和AI驱动的特点
- 展示Prophet的自主进化能力
- 包含适当的emoji
- 英文
- 标题格式: "🤖 Today in Prophet - [日期]"`
        }]
      })

      const content = message.content[0].type === 'text' ? message.content[0].text : ''

      // 创建GitHub Discussion
      await this.createDiscussion({
        title: content.split('\n')[0] || `🤖 Today in Prophet - ${dailyData.date}`,
        body: content
      })

      console.log('[GitHubAutoManager] ✅ 每日更新已发布')
    } catch (error) {
      console.error('[GitHubAutoManager] 每日更新失败:', error)
    }
  }

  /**
   * 获取GitHub统计数据
   */
  private async getGitHubStats(): Promise<GitHubStats> {
    try {
      // 获取仓库信息
      const { data: repo } = await this.octokit.rest.repos.get({
        owner: this.owner,
        repo: this.repo
      })

      // 获取issues统计
      const { data: openIssues } = await this.octokit.rest.issues.listForRepo({
        owner: this.owner,
        repo: this.repo,
        state: 'open',
        per_page: 1
      })

      const { data: closedIssues } = await this.octokit.rest.issues.listForRepo({
        owner: this.owner,
        repo: this.repo,
        state: 'closed',
        per_page: 1
      })

      // 本地Git统计（如果在仓库目录中）
      let totalCommits = 0
      try {
        totalCommits = parseInt(
          execSync('git rev-list --count HEAD', { encoding: 'utf-8' }).trim()
        )
      } catch {
        // 如果不在Git仓库中，使用0
        totalCommits = 0
      }

      return {
        totalCommits,
        totalStars: repo.stargazers_count,
        totalForks: repo.forks_count,
        totalWatchers: repo.subscribers_count,
        openIssues: openIssues.length > 0 ? repo.open_issues_count : 0,
        closedIssues: closedIssues.length,
        lastUpdate: new Date().toISOString().split('T')[0]
      }
    } catch (error) {
      console.error('[GitHubAutoManager] 获取stats失败:', error)
      // 返回默认值
      return {
        totalCommits: 0,
        totalStars: 0,
        totalForks: 0,
        totalWatchers: 0,
        openIssues: 0,
        closedIssues: 0,
        lastUpdate: new Date().toISOString().split('T')[0]
      }
    }
  }

  /**
   * 更新README中的badges
   */
  private updateBadges(readme: string, stats: GitHubStats): string {
    // 更新commits badge
    readme = readme.replace(
      /!\[Commits\]\(https:\/\/img\.shields\.io\/badge\/commits-\d+/g,
      `![Commits](https://img.shields.io/badge/commits-${stats.totalCommits}`
    )

    // 更新auto-updated badge
    readme = readme.replace(
      /!\[Auto-Updated\]\(https:\/\/img\.shields\.io\/badge\/auto--updated-[\d-]+/g,
      `![Auto-Updated](https://img.shields.io/badge/auto--updated-${stats.lastUpdate}`
    )

    return readme
  }

  /**
   * 更新README中的stats表格
   */
  private updateStatsTable(readme: string, stats: GitHubStats): string {
    // 查找stats表格并更新
    const statsPattern = /\| Total Auto-Commits \| \d+ \|/
    if (statsPattern.test(readme)) {
      readme = readme.replace(
        statsPattern,
        `| Total Auto-Commits | ${stats.totalCommits} |`
      )
    }

    // 更新Last Update
    const updatePattern = /\*\*Last Update\*\*: .+/
    if (updatePattern.test(readme)) {
      readme = readme.replace(
        updatePattern,
        `**Last Update**: ${stats.lastUpdate}`
      )
    }

    return readme
  }

  /**
   * 使用AI生成issue回复
   */
  private async generateIssueReply(issue: any): Promise<string | null> {
    try {
      const message = await this.anthropic.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 1000,
        messages: [{
          role: 'user',
          content: `作为Prophet AI项目的AI维护者，回复这个GitHub issue：

标题: ${issue.title}
作者: ${issue.user.login}
内容: ${issue.body || '(空)'}

要求：
- 友好专业的语气
- 如果是bug报告，表示会调查并尽快修复
- 如果是功能请求，表示会考虑并评估优先级
- 如果是问题，提供具体帮助或指引
- 如果是重复issue，礼貌说明并关联原issue
- 强调Prophet是AI驱动的自动化系统
- 英文回复
- 简洁（200字以内）`
        }]
      })

      return message.content[0].type === 'text' ? message.content[0].text : null
    } catch (error) {
      console.error('[GitHubAutoManager] AI回复生成失败:', error)
      return null
    }
  }

  /**
   * 获取今日活动数据
   */
  private async getDailyData(): Promise<DailyUpdate> {
    try {
      const today = new Date().toISOString().split('T')[0]

      // Git统计
      const commits = execSync('git log --since="24 hours ago" --oneline | wc -l', {
        encoding: 'utf-8'
      }).trim()

      const filesChanged = execSync(
        'git diff --stat HEAD~10 | tail -1 | awk \'{print $1}\'',
        { encoding: 'utf-8' }
      ).trim()

      const linesAdded = execSync(
        'git log --since="24 hours ago" --numstat | awk \'{add += $1} END {print add}\'',
        { encoding: 'utf-8' }
      ).trim()

      const linesDeleted = execSync(
        'git log --since="24 hours ago" --numstat | awk \'{del += $2} END {print del}\'',
        { encoding: 'utf-8' }
      ).trim()

      // 提取亮点（最近commit messages）
      const commitMessages = execSync('git log --since="24 hours ago" --pretty=format:"%s"', {
        encoding: 'utf-8'
      })
        .split('\n')
        .filter(msg => msg.trim())
        .slice(0, 3)

      return {
        date: today,
        commits: parseInt(commits) || 0,
        filesChanged: parseInt(filesChanged) || 0,
        linesAdded: parseInt(linesAdded) || 0,
        linesDeleted: parseInt(linesDeleted) || 0,
        highlights: commitMessages
      }
    } catch (error) {
      // 返回默认值
      return {
        date: new Date().toISOString().split('T')[0],
        commits: 0,
        filesChanged: 0,
        linesAdded: 0,
        linesDeleted: 0,
        highlights: []
      }
    }
  }

  /**
   * 创建GitHub Discussion
   */
  private async createDiscussion(config: {
    title: string
    body: string
  }): Promise<void> {
    try {
      // 使用GitHub GraphQL API创建discussion
      // 注意：需要仓库启用Discussions功能

      // 暂时使用issue作为替代（如果discussions不可用）
      await this.octokit.rest.issues.create({
        owner: this.owner,
        repo: this.repo,
        title: config.title,
        body: config.body,
        labels: ['auto-generated', 'daily-update']
      })

      console.log('[GitHubAutoManager] ✅ Discussion/Issue已创建')
    } catch (error) {
      console.error('[GitHubAutoManager] Discussion创建失败:', error)
    }
  }

  /**
   * 定时每日更新
   */
  private scheduleDailyUpdate(): void {
    const scheduleNext = () => {
      const now = new Date()
      const tomorrow = new Date(now)
      tomorrow.setDate(tomorrow.getDate() + 1)
      tomorrow.setHours(9, 17, 0, 0) // 早上9:17

      const delay = tomorrow.getTime() - now.getTime()

      setTimeout(async () => {
        if (this.isRunning) {
          await this.generateDailyUpdate()
        }
        scheduleNext() // 安排下一次
      }, delay)
    }

    scheduleNext()
  }

  /**
   * 获取状态
   */
  getStatus(): { isRunning: boolean; owner: string; repo: string } {
    return {
      isRunning: this.isRunning,
      owner: this.owner,
      repo: this.repo
    }
  }
}
