/**
 * 视频脚本生成器
 * 自动生成病毒式视频脚本
 */

import Anthropic from '@anthropic-ai/sdk';
import * as fs from 'fs/promises';
import * as path from 'path';

interface VideoScript {
  title: string;
  duration: number;
  platform: 'youtube' | 'tiktok' | 'bilibili' | 'twitter';
  scenes: Scene[];
  voiceover: string;
  bgm: string;
  hashtags: string[];
}

interface Scene {
  timestamp: string;
  duration: number;
  visual: string;
  text: string;
  action: string;
}

export class VideoScriptGenerator {
  private anthropic: Anthropic;

  constructor() {
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY || ''
    });
  }

  /**
   * 生成病毒式视频脚本
   */
  async generateViralScript(data: {
    totalTodos: number;
    autoCommits: number;
    runningDays: number;
    projects: number;
  }): Promise<VideoScript> {
    const prompt = `你是顶级短视频编导。创建一个30-60秒的病毒式视频脚本，展示Prophet自动化代码进化。

数据:
- 监控项目: ${data.projects}个
- 自动提交: ${data.autoCommits}次
- TODO处理: ${data.totalTodos}个
- 运行天数: ${data.runningDays}天

要求:
1. 开场3-5秒抓住眼球
2. 中段展示核心功能（实际录屏）
3. 结尾5秒CTA
4. 每个场景标注时间戳、视觉效果、文字
5. 适合抖音/B站/YouTube Shorts

返回JSON格式:
{
  "title": "视频标题",
  "duration": 45,
  "platform": "tiktok",
  "scenes": [
    {
      "timestamp": "0:00",
      "duration": 5,
      "visual": "黑屏+白色大字",
      "text": "凌晨3点，我睡着了",
      "action": "文字逐字浮现"
    }
  ],
  "voiceover": "完整旁白文案",
  "bgm": "Epic电子音乐",
  "hashtags": ["#AI", "#自动化"]
}`;

    const message = await this.anthropic.messages.create({
      model: 'claude-sonnet-4-5-20250929',
      max_tokens: 3000,
      messages: [{ role: 'user', content: prompt }]
    });

    const responseText = message.content[0].type === 'text'
      ? message.content[0].text
      : '';

    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('无法解析AI响应');
    }

    const script = JSON.parse(jsonMatch[0]);

    // 保存脚本
    await this.saveScript(script);

    return script;
  }

  /**
   * 生成录制指南
   */
  async generateRecordingGuide(script: VideoScript): Promise<string> {
    const guide = `# 🎬 Prophet 病毒视频录制指南

## 视频信息
- 标题: ${script.title}
- 时长: ${script.duration}秒
- 平台: ${script.platform}

## 录制前准备

### 1. 技术准备
- [ ] 清理3个项目终端输出
- [ ] 启动Prophet Central Dashboard (http://localhost:3001)
- [ ] 准备OBS/QuickTime录屏
- [ ] 测试麦克风音质
- [ ] 关闭通知和干扰

### 2. 内容准备
- [ ] 确保Prophet正在运行
- [ ] 准备展示的commit记录
- [ ] 准备TODO对比数据
- [ ] 准备dashboard截图

## 分镜录制

${script.scenes.map((scene, i) => `
### Scene ${i + 1}: ${scene.timestamp}
**时长**: ${scene.duration}秒
**视觉**: ${scene.visual}
**文字**: "${scene.text}"
**动作**: ${scene.action}

**录制要点**:
${this.getRecordingTips(scene)}
`).join('\n')}

## 后期制作

### 1. 剪辑
- 使用剪映/Final Cut Pro
- 添加字幕（大字体，高对比度）
- 调整节奏（快速剪辑）

### 2. 音频
- BGM: ${script.bgm}
- 旁白: ${script.voiceover ? '是' : '否'}
- 音效: 击键声、提示音

### 3. 特效
- 场景转场: 快速滑动
- 文字动画: 打字机效果
- 高亮重点: 红框、箭头

## 发布清单

### 文案
\`\`\`
${this.generatePublishCaption(script)}
\`\`\`

### 标签
${script.hashtags.join(' ')}

### 封面
- 使用第3-5秒的最震撼画面
- 添加文字: "${script.title}"
- 高对比度，易识别

## 发布时机

**最佳时间**:
- 抖音/快手: 19:00-21:00
- B站: 20:00-22:00
- YouTube Shorts: 美东时间 9:00-11:00
- Twitter: 美东时间 8:00-10:00

## 监控指标

发布后24小时内关注:
- [ ] 播放量 (目标: 10,000+)
- [ ] 点赞率 (目标: 5%+)
- [ ] 评论数 (目标: 50+)
- [ ] 转发数 (目标: 100+)
- [ ] 前往GitHub的点击

## 应急预案

如果12小时内播放<1000:
1. 调整标题和封面
2. 在相关社区转发
3. 找KOL帮忙转发
4. 付费推广 ($50-100)

---

Generated by Prophet Marketing Engine
${new Date().toISOString()}
`;

    // 保存指南
    const dir = '/Users/zhangjingwei/Desktop/New CC/.marketing-content/recording-guides';
    await fs.mkdir(dir, { recursive: true });
    const filepath = path.join(dir, `guide_${Date.now()}.md`);
    await fs.writeFile(filepath, guide);

    return guide;
  }

  private getRecordingTips(scene: Scene): string {
    const tips = [
      '- 保持画面稳定，不要晃动',
      '- 确保文字清晰可读',
      '- 控制好时长，不要超时'
    ];

    if (scene.visual.includes('终端')) {
      tips.push('- 放大终端字体（至少18px）');
      tips.push('- 使用高对比度配色');
    }

    if (scene.visual.includes('dashboard')) {
      tips.push('- 确保数据实时更新');
      tips.push('- 突出关键指标变化');
    }

    return tips.join('\n');
  }

  private generatePublishCaption(script: VideoScript): string {
    return `${script.title}

${script.voiceover.split('\n')[0]}

🔗 GitHub: github.com/prophet-ai
🌐 试用: agentforge.live

${script.hashtags.join(' ')}`;
  }

  private async saveScript(script: VideoScript): Promise<void> {
    const dir = '/Users/zhangjingwei/Desktop/New CC/.marketing-content/video-scripts';
    await fs.mkdir(dir, { recursive: true });

    const filepath = path.join(dir, `script_${Date.now()}.json`);
    await fs.writeFile(filepath, JSON.stringify(script, null, 2));

    console.log(`[VideoScript] ✅ 脚本已保存: ${filepath}`);
  }
}
